mysite/blog/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('articles/', views.ArticlesListView.as_view(), name='articles'),
    path('articles/<int:article_id>', views.article, name='article'),
    path('articles/new', views.NewArticleCreateView.as_view(), name='new-article'),
    path('articles/<int:pk>/update', views.ArticleUpdateView.as_view(), name='article-update'),
    path('articles/<int:pk>/delete', views.ArticleDeleteView.as_view(), name='article-delete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField


class Article(models.Model):
    title = models.CharField('Title', max_length=200)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField('Date', auto_now_add=True)
    text = HTMLField()

    def __str__(self):
        return f'{self.title} ({self.author})'

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    @property
    def comments_total(self):
        all_comments = ArticleComment.objects.filter(article=self.id)
        return len(all_comments)


class ArticleComment(models.Model):
    article = models.ForeignKey('Article', on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    commentator_name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    commentator_email = models.CharField('Email', max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Comment', max_length=2000)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

mysite/blog/views.py
from .models import Article
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.contrib.auth.forms import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def index(request):
    return render(request, 'index.html')


class ArticlesListView(generic.ListView):
    model = Article
    template_name = 'articles.html'
    paginate_by = 2

    def get_queryset(self):
        return Article.objects.order_by('-date')


def article(request, article_id):
    single_article = get_object_or_404(Article, pk=article_id)
    return render(request, 'article.html', {'article': single_article})


class NewArticleCreateView(LoginRequiredMixin, generic.CreateView):
    model = Article
    fields = ['title', 'text']
    success_url = "/blog/articles/"
    template_name = 'article_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Article
    fields = ['title', 'text']
    success_url = "/blog/articles/"
    template_name = 'article_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        cur_article = self.get_object()
        return self.request.user == cur_article.author


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Article
    success_url = "/blog/articles/"
    template_name = 'article_delete.html'

    def test_func(self):
        cur_article = self.get_object()
        return self.request.user == cur_article.author


@csrf_protect
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Username {username} is already in use!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Email {email} is already in use!')
                    return redirect('register')
                else:
                    User.objects.create_user(username=username, email=email, password=password)
        else:
            messages.error(request, 'Passwords do not match!')
            return redirect('register')
    return render(request, 'register.html')

mysite/blog/templates/article.html
{% extends "base.html" %}

{% block content %}
    <div class="container article">
    <h4>{{ article.title }}</h4>
    <hr/>
    <p>{{ article.text|safe }}</p>
    <strong>{{ article.author }}</strong>
    </div>
    <hr>
    <h4>Comments:</h4>
    {% if article.comments.all %}
        {% for com in article.comments.all %}
          <hr>
          <strong>{{ com.commentator_name }}, {{ com.commentator_email }}</strong>, <em>{{ com.date_created}}</em>
          <p>{{ com.content }}</p>
        {% endfor %}
    {% else %}
    <p>The order has no comments.</p>
    {% endif %}
{% endblock %}

mysite/blog/templates/article_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete article</legend>
            <h2>Are you sure you want to delete this article?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, delete it</button>
            <a class="btn btn-outline-secondary" href="{% url 'articles' %}">Cancel</a>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/blog/templates/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New article</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/blog/templates/articles.html
{% extends "base.html" %}

{% block content %}
  <h1>All articles</h1>
  {% if article_list %}
  <ul>
    {% for article in article_list %}
      <li>
          <h5>{{ article.title }}</h5>
          <p>{{ article.text|truncatechars:400|safe }} &nbsp <a href="{% url 'article' article.id %}">Read more...</a></p>
          <br>
          <strong>author: {{article.author}}</strong>
          <p>({{ article.comments_total }} comments)</p>
        {% if article.author == user %}
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'article-update' article.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'article-delete' article.id %}">Delete</a>
        {% endif %}
          <hr>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No articles.</p>
  {% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">back</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
      <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
    </svg>
    Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'articles' %}">Articles</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="#">
            <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
            </svg>
          {{ user.get_username }}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'new-article'%}?next=/blog">New article</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Logout</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registration</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

mysite/blog/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>This is a home page!</h1>
{% endblock %}

mysite/blog/templates/register.html
{% extends "base.html" %}

{% block content %}

<div>
    <h3>Registration</h3><br/>
    <form method="post">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="username">User name</label>
            <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
            <small id="usernameHelp" class="form-text text-muted">Max 150 simbols.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <small id="emailHelp" class="form-text text-muted">Only for password reset!</small>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
            <small id="pwdHelp" class="form-text text-muted">Minimum length is 8 characters. Must include at least one
                letter (a–z) and one number (0–9).</small>
        </div>
        <div class="form-group">
            <label for="password2">Re-Password</label>
            <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
        </div>
        <button type="submit" class="btn btn-primary register-button">Confirm</button>
    </form>
    <p>Already have an account? <a href="/login"><strong>Login.</strong></a></p>
</div>

{% endblock %}